server.port: 8080

spring.datasource.driver-class-name: com.mysql.cj.jdbc.Driver

spring:
  application.name: main-service
  datasource:
    url: jdbc:mysql://localhost:3306/bugtracker
    username: root
    password: root-password
  jpa.hibernate:
    ddl-auto: validate
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
          audiences: >
            523144607813-fnng3pmai446jt0ajc012aav6kedo8u4.apps.googleusercontent.com
      client:
        registration:
          google:
            client-id: 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