# version: '3.1'

services:
  db:
    image: mysql
    restart: always
    networks:
      - bugtracker-dev
    ports:
      - "3306:3306"
    volumes:
      - bugtracker-mysql-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: bugtracker
      MYSQL_ROOT_PASSWORD: root-password

networks:
  bugtracker-dev:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.host_binding_ipv4: "127.0.0.1"

volumes:
  bugtracker-mysql-data:
    external: true