# version: '3.1'

services:
  backend:
    image: bugtracker
    container_name: bugtracker
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - bugtracker-dev
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/bugtracker
  db:
    image: mysql
    container_name: db
    restart: always
    networks:
      - bugtracker-dev
    ports:
      - "3306:3306"
    volumes:
      - bugtracker-mysql-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: bugtracker
      MYSQL_ROOT_PASSWORD: root-password

networks:
  bugtracker-dev:
    name: bugtracker-dev

volumes:
  bugtracker-mysql-data:
    external: true