# version: '3.1'

services:
  backend:
    image: bugtracker
    container_name: bugtracker
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - bugtracker-dev
    ports:
      - "8080:8080"
    volumes:
      - bugtracker-user-content:/user-content
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/bugtracker
  db:
    image: mysql
    container_name: db
    networks:
      - bugtracker-dev
    ports:
      - "3306:3306"
    volumes:
      - bugtracker-mysql-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: bugtracker
      MYSQL_ROOT_PASSWORD: root-password
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u bugtracker --password=root-password
      start_period: 5s
      interval: 5s
      retries: 5
      timeout: 5s

networks:
  bugtracker-dev:
    name: bugtracker-dev
    driver_opts:
      com.docker.network.enable_ipv6: "false"
      com.docker.network.enable_ipv4: "true"

volumes:
  bugtracker-user-content:
    external: false
  bugtracker-mysql-data:
    external: false