server.port: 8080

spring:
    config:
        import: optional:file:.env[.properties]
    jackson.date-format: yyyy-MM-dd HH:mm:ss
    application.name: main-service
    datasource:
        url: ${DB_URL}
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa.hibernate:
        ddl-auto: validate
    servlet.multipart:
        max-file-size: 1MB
        max-request-size: 10MB
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: ${GOOGLE_ISSUER_URI}
                    jwk-set-uri: ${GOOGLE_JWK_SET_URI}
                    audiences: ${GOOGLE_JWT_AUDIENCE}
            client:
                registration:
                    google:
                        client-id: ${GOOGLE_CLIENT_ID}
