server.port: 8093

spring:
  application.name: project-table-issue-service
  datasource:
    url: jdbc:mysql://localhost:3306/Bugtracker2
    username: root
    password: root-password
  cloud.config.enabled: false
  jpa.hibernate:
    naming-strategy: PhysicalNamingStrategyStandardImpl
    ddl-auto: update

# security.enable.csrf: false
# management.endpoints.web.exposure.include = "*"
